import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const universities = [
  {
    name: "Khalifa University",
    country: "ОАЭ",
    city: "Abu Dhabi",
    worldRanking: "QS #230 (2024)",
    topMajors: ["Petroleum Engineering", "Biomedical Engineering", "Electrical Engineering"],
    allMajors: ["Petroleum Engineering", "Biomedical Engineering", "Electrical Engineering", "Aerospace Engineering", "Chemical Engineering", "Civil Engineering", "Computer Science", "Mechanical Engineering", "Nuclear Engineering"],
    tuitionMin: 8200,
    tuitionMax: 12300,
    hasDormitory: true,
    website: "https://www.ku.ac.ae",
    founded: 2007,
    studentCount: 4300,
    language: "English",
    description: "Khalifa University is a top-ranked research university focusing on science, engineering and medicine. The university brings together the best in science, engineering and medicine in the UAE, to offer specialized degrees that can take promising high school graduates all the way to top-rated doctorate degree holders.",
    features: ["Research-intensive university", "State-of-the-art facilities", "Strong industry partnerships", "Full scholarships available for Emiratis"],
  },
  {
    name: "United Arab Emirates University",
    country: "ОАЭ",
    city: "Al Ain",
    worldRanking: "QS #290 (2024)",
    topMajors: ["Engineering", "Medicine & Health Sciences", "Business & Economics"],
    allMajors: ["Engineering", "Medicine", "Business", "Economics", "Education", "Food & Agriculture", "Humanities", "IT", "Law", "Science"],
    tuitionMin: 8400,
    tuitionMax: 32700,
    hasDormitory: true,
    website: "https://www.uaeu.ac.ae",
    founded: 1976,
    studentCount: 14900,
    language: "English/Arabic",
    description: "United Arab Emirates University is the oldest university in the UAE and consistently ranks as one of the top research universities in the region.",
    features: ["First national university", "Comprehensive research programs", "International partnerships", "Beautiful campus"],
  },
  {
    name: "American University of Sharjah",
    country: "ОАЭ",
    city: "Sharjah",
    worldRanking: "QS #360 (2024)",
    topMajors: ["Engineering", "Business Administration", "Architecture"],
    allMajors: ["Engineering", "Business", "Architecture", "Arts & Sciences", "Communication", "Design"],
    tuitionMin: 29300,
    tuitionMax: 29300,
    hasDormitory: true,
    website: "https://www.aus.edu",
    founded: 1997,
    studentCount: 6000,
    language: "English",
    description: "American University of Sharjah is an independent, not-for-profit coeducational institution based on the American model of higher education.",
    features: ["US-accredited degrees", "Diverse student body", "English language instruction", "Modern facilities"],
  },
  {
    name: "University of Sharjah",
    country: "ОАЭ",
    city: "Sharjah",
    worldRanking: "QS #465 (2024)",
    topMajors: ["Engineering", "Medicine", "Business Administration"],
    allMajors: ["Engineering", "Medicine", "Business", "Law", "Communication", "Design", "Fine Arts", "Health Sciences", "Pharmacy", "Science"],
    tuitionMin: 8200,
    tuitionMax: 24500,
    hasDormitory: true,
    website: "https://www.sharjah.ac.ae",
    founded: 1997,
    studentCount: 19246,
    language: "English/Arabic",
    description: "University of Sharjah is a comprehensive university serving students from all around the world with a particular focus on innovation and research.",
    features: ["Large student population", "Research centers", "International collaboration", "Scholarships available"],
  },
  {
    name: "Abu Dhabi University",
    country: "ОАЭ",
    city: "Abu Dhabi",
    worldRanking: "QS #251-300 (2024)",
    topMajors: ["Business & Economics", "Engineering", "Health Sciences"],
    allMajors: ["Business", "Engineering", "Health Sciences", "Arts & Sciences", "Law", "Education"],
    tuitionMin: 13600,
    tuitionMax: 16300,
    hasDormitory: true,
    website: "https://www.adu.ac.ae",
    founded: 2003,
    studentCount: 7500,
    language: "English",
    description: "Abu Dhabi University is one of the UAE's largest private universities, with over 7,500 students from over 90 countries.",
    features: ["Multiple campuses", "Industry partnerships", "Flexible learning options", "Career support"],
  },
  {
    name: "Istanbul Technical University",
    country: "Турция",
    city: "Istanbul",
    worldRanking: "QS #404 (2024)",
    topMajors: ["Engineering", "Architecture", "Computer Science"],
    allMajors: ["Engineering", "Architecture", "Computer Science", "Science & Letters", "Management", "Maritime Faculty", "Aeronautics & Astronautics"],
    tuitionMin: 1500,
    tuitionMax: 5000,
    hasDormitory: true,
    website: "https://www.itu.edu.tr",
    founded: 1773,
    studentCount: 30000,
    language: "Turkish/English",
    description: "Istanbul Technical University is one of the world's oldest technical universities with a long history dating back to 1773.",
    features: ["Historic institution", "Strong engineering programs", "Research excellence", "Affordable tuition"],
  },
  {
    name: "Koç University",
    country: "Турция",
    city: "Istanbul",
    worldRanking: "QS #431 (2024)",
    topMajors: ["Business Administration", "Engineering", "Economics"],
    allMajors: ["Business", "Engineering", "Economics", "Science", "Medicine", "Law", "Nursing", "Social Sciences & Humanities"],
    tuitionMin: 18000,
    tuitionMax: 19500,
    hasDormitory: true,
    website: "https://www.ku.edu.tr",
    founded: 1993,
    studentCount: 5500,
    language: "English",
    description: "Koç University is a private, non-profit institution, established in Istanbul in 1993. The university is one of the top universities in Turkey and offers undergraduate and graduate programs.",
    features: ["Research university", "English instruction", "Strong international partnerships", "Modern campus"],
  },
  {
    name: "Bilkent University",
    country: "Турция",
    city: "Ankara",
    worldRanking: "QS #502 (2024)",
    topMajors: ["Computer Engineering", "Electrical and Electronic Engineering", "Industrial Engineering"],
    allMajors: ["Engineering", "Science", "Economics & Administrative Sciences", "Humanities & Letters", "Art, Design & Architecture", "Law", "Music & Performing Arts", "Applied Sciences"],
    tuitionMin: 16200,
    tuitionMax: 16950,
    hasDormitory: true,
    website: "https://www.bilkent.edu.tr",
    founded: 1984,
    studentCount: 13000,
    language: "English",
    description: "Bilkent University is Turkey's first private, nonprofit university and has distinguished itself as a premier institution of higher education.",
    features: ["First private university in Turkey", "English medium instruction", "Research-focused", "Beautiful campus"],
  },
  {
    name: "Hacettepe University",
    country: "Турция",
    city: "Ankara",
    worldRanking: "QS #561-570 (2024)",
    topMajors: ["Medicine", "Pharmacy", "Engineering"],
    allMajors: ["Medicine", "Pharmacy", "Engineering", "Science", "Economics & Administrative Sciences", "Communication", "Fine Arts", "Law", "Education", "Dentistry", "Health Sciences"],
    tuitionMin: 214,
    tuitionMax: 7000,
    hasDormitory: true,
    website: "https://www.hacettepe.edu.tr",
    founded: 1967,
    studentCount: 45000,
    language: "Turkish/English",
    description: "Hacettepe University is one of Turkey's leading universities and is particularly known for its medical school and healthcare programs.",
    features: ["Leading medical school", "Research hospitals", "Comprehensive programs", "Very affordable for state university"],
  },
  {
    name: "Istanbul University",
    country: "Турция",
    city: "Istanbul",
    worldRanking: "QS #801-850 (2024)",
    topMajors: ["Medicine", "Law", "Pharmacy"],
    allMajors: ["Medicine", "Law", "Pharmacy", "Dentistry", "Engineering", "Science", "Economics", "Communication", "Education", "Theology", "Aquatic Sciences"],
    tuitionMin: 1600,
    tuitionMax: 10800,
    hasDormitory: true,
    website: "https://www.istanbul.edu.tr",
    founded: 1453,
    studentCount: 58809,
    language: "Turkish/English",
    description: "Istanbul University is the oldest university in Turkey and one of the most prestigious. With roots dating back to 1453, it offers a rich academic tradition.",
    features: ["Oldest Turkish university", "Historic institution", "Large student body", "Central location in Istanbul"],
  },
  {
    name: "Peking University",
    country: "Китай",
    city: "Beijing",
    worldRanking: "QS #17 (2024)",
    topMajors: ["Mathematics", "Physics", "Economics"],
    allMajors: ["Mathematics", "Physics", "Economics", "Chemistry", "Computer Science", "Life Sciences", "Engineering", "Medicine", "Law", "International Relations", "Chinese Literature", "Philosophy"],
    tuitionMin: 7100,
    tuitionMax: 25600,
    hasDormitory: true,
    website: "https://www.pku.edu.cn",
    founded: 1898,
    studentCount: 46113,
    language: "Chinese/English",
    description: "Peking University is a comprehensive research university and a member of the C9 League. It is one of China's most prestigious universities and ranks among the best in Asia.",
    features: ["Top-ranked in Asia", "Beautiful campus", "Strong in humanities and sciences", "International programs"],
  },
  {
    name: "Tsinghua University",
    country: "Китай",
    city: "Beijing",
    worldRanking: "QS #25 (2024)",
    topMajors: ["Engineering", "Computer Science", "Architecture"],
    allMajors: ["Engineering", "Computer Science", "Architecture", "Science", "Economics & Management", "Humanities", "Law", "Medicine", "Arts"],
    tuitionMin: 4100,
    tuitionMax: 6900,
    hasDormitory: true,
    website: "https://www.tsinghua.edu.cn",
    founded: 1911,
    studentCount: 37000,
    language: "Chinese/English",
    description: "Tsinghua University is consistently ranked as one of China's best and most influential universities, particularly renowned for its engineering and technology programs.",
    features: ["MIT of China", "Leading engineering programs", "Strong tech industry connections", "Beautiful historical campus"],
  },
  {
    name: "Fudan University",
    country: "Китай",
    city: "Shanghai",
    worldRanking: "QS #50 (2024)",
    topMajors: ["Medicine", "Economics", "International Relations"],
    allMajors: ["Medicine", "Economics", "International Relations", "Law", "Management", "Journalism", "Computer Science", "Mathematics", "Physics", "Chemistry", "Life Sciences"],
    tuitionMin: 6300,
    tuitionMax: 11000,
    hasDormitory: true,
    website: "https://www.fudan.edu.cn",
    founded: 1905,
    studentCount: 35000,
    language: "Chinese/English",
    description: "Fudan University is one of China's most prestigious and selective universities. It is a comprehensive research university particularly strong in social sciences and medicine.",
    features: ["Comprehensive programs", "Strong in medicine and social sciences", "Located in Shanghai", "International partnerships"],
  },
  {
    name: "Shanghai Jiao Tong University",
    country: "Китай",
    city: "Shanghai",
    worldRanking: "QS #51 (2024)",
    topMajors: ["Engineering", "Medicine", "Management"],
    allMajors: ["Engineering", "Medicine", "Management", "Science", "Economics", "Law", "Agriculture", "Liberal Arts"],
    tuitionMin: 3800,
    tuitionMax: 11000,
    hasDormitory: true,
    website: "https://www.sjtu.edu.cn",
    founded: 1896,
    studentCount: 43452,
    language: "Chinese/English",
    description: "Shanghai Jiao Tong University is one of China's oldest and most prestigious universities, particularly known for engineering, medicine, and business programs.",
    features: ["Historic university", "Strong engineering programs", "Top medical school", "Located in Shanghai"],
  },
  {
    name: "University of Science and Technology of China",
    country: "Китай",
    city: "Hefei",
    worldRanking: "QS #137 (2024)",
    topMajors: ["Physics", "Chemistry", "Computer Science"],
    allMajors: ["Physics", "Chemistry", "Computer Science", "Mathematics", "Life Sciences", "Engineering Science", "Management", "Earth & Space Sciences"],
    tuitionMin: 3780,
    tuitionMax: 5100,
    hasDormitory: true,
    website: "https://www.ustc.edu.cn",
    founded: 1958,
    studentCount: 16000,
    language: "Chinese/English",
    description: "USTC is a highly selective research university focused on science and technology. It is known for producing many of China's top scientists and researchers.",
    features: ["Elite science university", "Small class sizes", "Research focus", "Strong in physics and computer science"],
  },
]

async function main() {
  console.log('Starting to seed international universities...')

  for (const university of universities) {
    const created = await prisma.internationalUniversity.create({
      data: university,
    })
    console.log(`Created ${created.name}`)
  }

  console.log(`Seeded ${universities.length} international universities`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
