import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const uaeUniversities = [
  // === ОБНОВЛЕНИЕ СУЩЕСТВУЮЩИХ 5 ===
  {
    name: "Khalifa University",
    country: "ОАЭ",
    city: "Абу-Даби",
    worldRanking: "QS #177 (2026)",
    topMajors: ["Aerospace Engineering", "Mechanical Engineering", "Petroleum Engineering", "Electrical & Computer Engineering", "Biomedical Engineering", "Cybersecurity", "Artificial Intelligence", "Nuclear Engineering"],
    allMajors: ["Aerospace Engineering", "Mechanical Engineering", "Petroleum Engineering", "Electrical Engineering", "Computer Engineering", "Biomedical Engineering", "Chemical Engineering", "Civil Engineering", "Computer Science", "Cybersecurity", "Artificial Intelligence", "Nuclear Engineering", "Mathematics", "Physics", "Chemistry"],
    tuitionMin: 20000,
    tuitionMax: 22000,
    hasDormitory: true,
    website: "https://www.ku.ac.ae",
    founded: 2007,
    studentCount: 4300,
    internationalStudents: 1300,
    language: "English",
    description: "Khalifa University — ведущий исследовательский университет ОАЭ, образованный в 2017 году объединением трёх вузов. Предлагает стипендии до 100% для международных студентов. Сильнейшие программы в инженерии и технологиях.",
    features: ["Исследовательский университет #1 в ОАЭ", "Стипендии до 100%", "ABET-аккредитация инженерных программ", "Центры исследований в робототехнике и ИИ", "Связи с энергетической индустрией"],
  },
  {
    name: "United Arab Emirates University",
    country: "ОАЭ",
    city: "Аль-Айн",
    worldRanking: "QS #229 (2026)",
    topMajors: ["Business Administration", "Engineering", "Medicine", "Information Technology", "Education", "Law", "Science", "Food & Agriculture"],
    allMajors: ["Business Administration", "Engineering", "Medicine", "Information Technology", "Education", "Law", "Science", "Food & Agriculture", "Humanities & Social Sciences", "Economics"],
    tuitionMin: 15700,
    tuitionMax: 26100,
    hasDormitory: true,
    website: "https://www.uaeu.ac.ae",
    founded: 1976,
    studentCount: 14900,
    internationalStudents: 2830,
    language: "English/Arabic",
    description: "Старейший и крупнейший университет ОАЭ, основанный шейхом Заидом. Современный кампус площадью 296 акров в Аль-Айне. Классифицирован как исследовательский интенсивный университет с сильнейшими программами в регионе.",
    features: ["Старейший университет ОАЭ", "Государственное финансирование", "Топ-5 в арабском регионе", "9 колледжей по всем основным направлениям", "Студенты из 82 стран"],
  },
  {
    name: "American University of Sharjah",
    country: "ОАЭ",
    city: "Шарджа",
    worldRanking: "QS #272 (2026)",
    topMajors: ["Architecture", "Civil Engineering", "Mechanical Engineering", "Business Administration", "Computer Science", "Biology", "Design Management", "Finance"],
    allMajors: ["Architecture", "Civil Engineering", "Mechanical Engineering", "Business Administration", "Computer Science", "Biology", "Design Management", "Finance", "Electrical Engineering", "Chemical Engineering", "Communication", "International Studies"],
    tuitionMin: 29300,
    tuitionMax: 29300,
    hasDormitory: true,
    website: "https://www.aus.edu",
    founded: 1997,
    studentCount: 4500,
    internationalStudents: 4000,
    language: "English",
    description: "Независимый некоммерческий вуз по модели американского liberal arts образования. Предлагает 28 специальностей, 45 миноров, 16 магистерских и 3 PhD программы. В мировом топе по доле международных студентов.",
    features: ["Американская модель образования", "AACSB-аккредитация бизнес-школы", "ABET-аккредитация инженерных программ", "90+ национальностей", "Основан правителем Шарджи"],
  },
  {
    name: "University of Sharjah",
    country: "ОАЭ",
    city: "Шарджа",
    worldRanking: "QS #328 (2026)",
    topMajors: ["Medicine", "Dental Surgery", "Pharmacy", "Law", "Engineering", "Business Administration", "Architecture", "Information Technology"],
    allMajors: ["Medicine", "Dental Surgery", "Pharmacy", "Law", "Engineering", "Business Administration", "Architecture", "Information Technology", "Communication", "Fine Arts", "Health Sciences", "Science"],
    tuitionMin: 12300,
    tuitionMax: 33800,
    hasDormitory: true,
    website: "https://www.sharjah.ac.ae",
    founded: 1997,
    studentCount: 21174,
    internationalStudents: 9240,
    language: "English/Arabic",
    description: "Один из крупнейших университетов ОАЭ с более чем 120 дисциплинами в 14 колледжах. Особенно сильная репутация в медицинских и стоматологических программах. Студенты из 100+ стран.",
    features: ["14 академических колледжей", "120+ дисциплин", "Сильные медицинские программы", "Стипендии 25-50%", "Основан правителем Шарджи"],
  },
  {
    name: "Abu Dhabi University",
    country: "ОАЭ",
    city: "Абу-Даби",
    worldRanking: "QS #391 (2026)",
    topMajors: ["Business Administration", "Engineering", "Law", "Architecture", "Health Sciences", "Information Technology", "Education"],
    allMajors: ["Business Administration", "Civil Engineering", "Mechanical Engineering", "Electrical Engineering", "Law", "Architecture", "Health Sciences", "Information Technology", "Education", "Arts & Sciences"],
    tuitionMin: 9000,
    tuitionMax: 17000,
    hasDormitory: true,
    website: "https://www.adu.ac.ae",
    founded: 2003,
    studentCount: 10330,
    internationalStudents: 5000,
    language: "English/Arabic",
    description: "Частный университет с 65+ академическими программами в 5 колледжах. Имеет одновременно WASC и EQUIS/AACSB аккредитации бизнес-школы — это есть только у 1% бизнес-школ в мире.",
    features: ["WASC-аккредитация", "EQUIS и AACSB двойная аккредитация (топ 1%)", "ABET-аккредитация инженерных программ", "RIBA-аккредитация архитектуры", "Кампусы в Абу-Даби и Аль-Айне"],
  },

  // === НОВЫЕ 15 ВУЗОВ ===
  {
    name: "American University in Dubai",
    country: "ОАЭ",
    city: "Дубай",
    worldRanking: "QS #678 (2026)",
    topMajors: ["Business Administration", "Architecture", "Interior Design", "Visual Communication", "International Studies", "Psychology", "Communication & Media", "Information Technology"],
    allMajors: ["Business Administration", "Architecture", "Interior Design", "Visual Communication", "International Studies", "Psychology", "Communication & Media", "Information Technology", "Graphic Design", "Finance", "Marketing"],
    tuitionMin: 18000,
    tuitionMax: 30600,
    hasDormitory: true,
    website: "https://www.aud.edu",
    founded: 1995,
    studentCount: 1900,
    internationalStudents: 1700,
    language: "English",
    description: "Частный вуз с американской моделью образования и двойной аккредитацией — SACSCOC (США) и Министерство образования ОАЭ. Один из немногих вузов региона с одновременно американской и локальной аккредитацией.",
    features: ["Двойная аккредитация SACSCOC и UAE MOE", "Американская программа обучения", "Сильная школа архитектуры и дизайна", "100+ национальностей", "Центральное расположение в Дубае"],
  },
  {
    name: "Zayed University",
    country: "ОАЭ",
    city: "Абу-Даби",
    worldRanking: "QS #595 (2026)",
    topMajors: ["Business Administration", "Communication & Media", "Computer Science", "Education", "Finance", "Marketing", "Creative Design", "Information Technology"],
    allMajors: ["Business Administration", "Communication & Media", "Computer Science", "Education", "Finance", "Marketing", "Creative Design", "Information Technology", "Natural Sciences", "Mathematics & Statistics"],
    tuitionMin: 11000,
    tuitionMax: 19000,
    hasDormitory: true,
    website: "https://www.zu.ac.ae",
    founded: 1998,
    studentCount: 4000,
    language: "English/Arabic",
    description: "Государственный университет с кампусами в Абу-Даби и Дубае. Предлагает 35 программ бакалавриата и магистратуры. Сильный акцент на инновации и предпринимательство.",
    features: ["Государственный университет", "Два кампуса: Абу-Даби и Дубай", "AACSB-аккредитация бизнес-школы", "Акцент на инновации и предпринимательство"],
  },
  {
    name: "Heriot-Watt University Dubai",
    country: "ОАЭ",
    city: "Дубай",
    worldRanking: "QS #287 (2026)",
    topMajors: ["Mechanical Engineering", "Computer Science", "Business Management", "Construction Project Management", "Data Science", "Cybersecurity", "Psychology", "Interior Design"],
    allMajors: ["Mechanical Engineering", "Computer Science", "Business Management", "Construction Project Management", "Data Science", "Cybersecurity", "Psychology", "Interior Design", "Fashion & Textiles", "Accounting & Finance", "Civil Engineering"],
    tuitionMin: 15800,
    tuitionMax: 20400,
    hasDormitory: true,
    website: "https://www.hw.ac.uk/dubai",
    founded: 2005,
    studentCount: 5100,
    internationalStudents: 4600,
    language: "English",
    description: "Первый зарубежный университетский кампус в Дубае. Новый кампус был открыт королём Карлом III в 2023 году. Дипломы идентичны выпускникам кампуса в Эдинбурге.",
    features: ["Первый зарубежный вуз в Dubai Academic City", "5 звёзд KHDA", "Дипломы идентичны Эдинбургу", "125+ национальностей", "Кампус открыт королём Карлом III (2023)"],
  },
  {
    name: "University of Birmingham Dubai",
    country: "ОАЭ",
    city: "Дубай",
    worldRanking: "QS #80 (2026)",
    topMajors: ["Computer Science", "Mechanical Engineering", "Business Management", "Psychology", "Law", "Artificial Intelligence", "Economics", "Education"],
    allMajors: ["Computer Science", "Mechanical Engineering", "Business Management", "Psychology", "Law", "Artificial Intelligence", "Economics", "Education", "Accounting & Finance", "Digital Marketing"],
    tuitionMin: 22000,
    tuitionMax: 41000,
    hasDormitory: false,
    website: "https://www.birmingham.ac.uk/dubai",
    founded: 2018,
    studentCount: 3000,
    language: "English",
    description: "Филиал Бирмингемского университета — члена Russell Group. В 2025 открыт новый кампус площадью 50,000 м². Студенты получают тот же диплом, что и выпускники кампуса в Великобритании.",
    features: ["Russell Group университет", "Дипломы идентичны UK кампусу", "Новый кампус 50,000 м² (2025)", "~50 программ бакалавриата и магистратуры", "AACSB и AMBA аккредитация бизнес-школы"],
  },
  {
    name: "Middlesex University Dubai",
    country: "ОАЭ",
    city: "Дубай",
    worldRanking: "QS #801-850 (2026)",
    topMajors: ["Business Administration", "Accounting & Finance", "Psychology", "Law", "Computer Science", "Information Technology", "Media & Communications", "Fashion Design"],
    allMajors: ["Business Administration", "Accounting & Finance", "Psychology", "Law", "Computer Science", "Information Technology", "Media & Communications", "Fashion Design", "Education", "Health & Social Sciences"],
    tuitionMin: 13400,
    tuitionMax: 17200,
    hasDormitory: true,
    website: "https://www.mdx.ac.ae",
    founded: 2005,
    studentCount: 6300,
    internationalStudents: 5900,
    language: "English",
    description: "Филиал Middlesex University London. Первый вуз в ОАЭ, предлагающий очную британскую юридическую степень (LLB). 5 звёзд KHDA и аккредитация QAA.",
    features: ["5 звёзд KHDA", "Первый LLB в ОАЭ", "QAA-аккредитация", "CAA-аккредитация (2025)", "127 национальностей"],
  },
  {
    name: "Canadian University Dubai",
    country: "ОАЭ",
    city: "Дубай",
    worldRanking: "QS #604 (2026)",
    topMajors: ["Architecture & Interior Design", "Business Administration", "Engineering", "Communication & Media", "Applied Science & Technology", "MBA"],
    allMajors: ["Architecture", "Interior Design", "Business Administration", "Engineering", "Communication & Media", "Applied Science & Technology", "MBA", "Computer Networking Engineering", "Environmental Health Sciences"],
    tuitionMin: 17800,
    tuitionMax: 27500,
    hasDormitory: true,
    website: "https://www.cud.ac.ae",
    founded: 2006,
    studentCount: 1500,
    internationalStudents: 1400,
    language: "English",
    description: "Университет с канадской моделью обучения на Sheikh Zayed Road в центре Дубая. №1 в Дубае 4 года подряд по QS Arab Region Rankings, №21 в арабском регионе.",
    features: ["Канадская модель образования", "#1 в Дубае по QS Arab Rankings", "127 национальностей", "Центральное расположение на Sheikh Zayed Road", "Партнёрства с канадскими вузами"],
  },
  {
    name: "Ajman University",
    country: "ОАЭ",
    city: "Аджман",
    worldRanking: "QS #440 (2026)",
    topMajors: ["Pharmacy", "Dentistry", "Engineering", "Business Administration", "Information Technology", "Law", "Mass Communication", "Education"],
    allMajors: ["Pharmacy", "Dentistry", "Engineering", "Business Administration", "Information Technology", "Law", "Mass Communication", "Education", "Architecture", "Health Sciences"],
    tuitionMin: 9500,
    tuitionMax: 16400,
    hasDormitory: true,
    website: "https://www.ajman.ac.ae",
    founded: 1988,
    studentCount: 6085,
    internationalStudents: 4000,
    language: "English/Arabic",
    description: "Первый частный университет в GCC (1988) и первый вуз ОАЭ, принимающий иностранных студентов обоих полов. 9 колледжей. №3 в мире по доле международных студентов.",
    features: ["Первый частный вуз в GCC", "WSCUC и QAA аккредитация", "#3 в мире по доле иностранных студентов", "Сильные программы фармации и стоматологии", "70+ стран"],
  },
  {
    name: "University of Wollongong in Dubai",
    country: "ОАЭ",
    city: "Дубай",
    worldRanking: "QS #601-650 (2026)",
    topMajors: ["Business Administration", "Computer Science", "Engineering", "Information Technology", "Cybersecurity", "Finance", "Marketing", "Media & Communication"],
    allMajors: ["Business Administration", "Computer Science", "Engineering", "Information Technology", "Cybersecurity", "Finance", "Marketing", "Media & Communication", "Accounting", "Human Resource Management"],
    tuitionMin: 16400,
    tuitionMax: 24500,
    hasDormitory: false,
    website: "https://www.uowdubai.ac.ae",
    founded: 1993,
    studentCount: 3700,
    internationalStudents: 3500,
    language: "English",
    description: "Первый международный университет в ОАЭ (1993), филиал University of Wollongong (Австралия). 40+ признанных программ бакалавриата и магистратуры в 10 отраслевых секторах.",
    features: ["Первый международный вуз в ОАЭ", "AACSB-аккредитация бизнес-программ", "CAA-аккредитация", "TEQSA-аккредитация (Австралия)", "108+ национальностей"],
  },
  {
    name: "SP Jain School of Global Management",
    country: "ОАЭ",
    city: "Дубай",
    worldRanking: "Top 10 Asia-Pacific (MBA, Bloomberg)",
    topMajors: ["Global MBA", "Bachelor of Business Administration", "Master of Global Business", "Data Science", "International Business", "Artificial Intelligence"],
    allMajors: ["Global MBA", "BBA", "Master of Global Business", "Data Science", "International Business", "Artificial Intelligence", "Marketing", "Finance", "Entrepreneurship"],
    tuitionMin: 17640,
    tuitionMax: 36900,
    hasDormitory: true,
    website: "https://www.spjain.org",
    founded: 2004,
    studentCount: 600,
    internationalStudents: 500,
    language: "English",
    description: "Бизнес-школа с кампусами в Дубае, Мумбаи, Сингапуре и Сиднее. Уникальная модель multi-city — студенты учатся в нескольких городах мира. Конкурс 13% зачисляемых.",
    features: ["Multi-city обучение: Дубай-Мумбаи-Сингапур-Сидней", "TEQSA-аккредитация", "ABEST21-аккредитация MBA", "ACCA-аккредитация BBA", "Стипендии до $37,500"],
  },
  {
    name: "Murdoch University Dubai",
    country: "ОАЭ",
    city: "Дубай",
    worldRanking: "QS #423 (2026)",
    topMajors: ["Business Administration", "Computer Science", "Cybersecurity", "Information Systems", "Marketing", "Human Resources", "Media & Communication", "Engineering"],
    allMajors: ["Business Administration", "Computer Science", "Cybersecurity", "Information Systems", "Marketing", "Human Resources", "Media & Communication", "Engineering", "Psychology", "Criminology"],
    tuitionMin: 6800,
    tuitionMax: 24200,
    hasDormitory: true,
    website: "https://www.murdochuniversitydubai.com",
    founded: 2008,
    studentCount: 650,
    language: "English",
    description: "Филиал австралийского Murdoch University в Dubai International Academic City. Австралийские дипломы, аккредитованные регуляторами Австралии и ОАЭ. Небольшие группы для персонализированного обучения.",
    features: ["Австралийские дипломы", "CAA, KHDA и TEQSA аккредитация", "Небольшие группы", "Возможность перевода в кампус Перта", "19 программ в 8 направлениях"],
  },
  {
    name: "University of Dubai",
    country: "ОАЭ",
    city: "Дубай",
    worldRanking: "QS #701-750 (2026)",
    topMajors: ["Business Administration", "Law", "Electrical Engineering", "Computing & Information Systems", "Data Science", "Cybersecurity", "Accounting & Finance"],
    allMajors: ["Business Administration", "Law", "Electrical Engineering", "Computing & Information Systems", "Data Science", "Cybersecurity", "Accounting & Finance", "Marketing", "Human Resource Management"],
    tuitionMin: 15000,
    tuitionMax: 19100,
    hasDormitory: true,
    website: "https://ud.ac.ae",
    founded: 1997,
    studentCount: 1500,
    language: "English",
    description: "Частный университет, основанный Торгово-промышленной палатой Дубая. Фокус на бизнес, право и инженерию/IT. Золотой стандарт аккредитаций — AACSB и ABET.",
    features: ["Основан Dubai Chamber of Commerce", "AACSB-аккредитация бизнеса", "ABET-аккредитация IT программ", "26+ аккредитованных программ", "Тесные связи с бизнес-сообществом Дубая"],
  },
  {
    name: "Rochester Institute of Technology Dubai",
    country: "ОАЭ",
    city: "Дубай",
    worldRanking: "QS 4 Stars",
    topMajors: ["Electrical Engineering", "Mechanical Engineering", "Computer Engineering", "Business Administration", "Information Technology", "Service Leadership & Innovation"],
    allMajors: ["Electrical Engineering", "Mechanical Engineering", "Computer Engineering", "Business Administration", "Information Technology", "Service Leadership & Innovation", "Professional Studies"],
    tuitionMin: 18500,
    tuitionMax: 39100,
    hasDormitory: true,
    website: "https://www.rit.edu/dubai",
    founded: 2008,
    studentCount: 700,
    language: "English",
    description: "Некоммерческий филиал Rochester Institute of Technology (Нью-Йорк) в Dubai Silicon Oasis. Студенты могут учиться в кампусе RIT в Нью-Йорке. Все инженерные программы с ABET-аккредитацией.",
    features: ["ABET-аккредитация инженерии", "AACSB-аккредитация бизнеса", "Обучение в кампусе RIT New York", "Расположен в Dubai Silicon Oasis", "30% стипендия для международных студентов"],
  },
  {
    name: "Manipal Academy of Higher Education Dubai",
    country: "ОАЭ",
    city: "Дубай",
    worldRanking: "QS Top 200 Asia",
    topMajors: ["Computer Science", "Electrical Engineering", "Mechatronics", "Mechanical Engineering", "Business Administration", "Architecture", "Interior Design", "Biotechnology"],
    allMajors: ["Computer Science", "Electrical Engineering", "Mechatronics", "Mechanical Engineering", "Business Administration", "Architecture", "Interior Design", "Biotechnology", "Media & Communication", "Information Technology"],
    tuitionMin: 7500,
    tuitionMax: 14500,
    hasDormitory: true,
    website: "https://www.manipaldubai.com",
    founded: 2000,
    studentCount: 3100,
    internationalStudents: 2500,
    language: "English",
    description: "Филиал крупнейшего частного университета Индии. 50+ программ в инженерии, бизнесе, дизайне, архитектуре и науках. Одна из самых доступных стоимостей обучения в ОАЭ.",
    features: ["5 звёзд KHDA", "IET-аккредитация инженерных программ", "Филиал крупнейшего частного вуза Индии", "Доступная стоимость обучения", "50+ стран"],
  },
  {
    name: "Curtin University Dubai",
    country: "ОАЭ",
    city: "Дубай",
    worldRanking: "QS #174 (2026)",
    topMajors: ["Commerce", "Accounting", "Finance", "Marketing", "Engineering", "Mass Communication", "Supply Chain Management", "International Business"],
    allMajors: ["Commerce", "Accounting", "Finance", "Marketing", "Engineering", "Mass Communication", "Supply Chain Management", "International Business", "Human Resource Management", "Public Relations"],
    tuitionMin: 16000,
    tuitionMax: 23700,
    hasDormitory: false,
    website: "https://curtindubai.ac.ae",
    founded: 2017,
    studentCount: 300,
    language: "English",
    description: "Филиал крупнейшего университета Западной Австралии. Австралийские дипломы с возможностью трансфера между глобальными кампусами Curtin. Имеет наивысший рейтинг QS Five Stars Plus.",
    features: ["QS Five Stars Plus (наивысший рейтинг)", "KHDA и CAA аккредитация", "Австралийские дипломы", "Трансфер между кампусами", "22 курса в 8 направлениях"],
  },
  {
    name: "Amity University Dubai",
    country: "ОАЭ",
    city: "Дубай",
    worldRanking: "Forbes Top Education Provider",
    topMajors: ["Business Administration", "Data Science", "Engineering", "Architecture", "Interior Design", "Journalism & Mass Communication", "Information Technology", "Fashion Design"],
    allMajors: ["Business Administration", "Data Science", "Engineering", "Architecture", "Interior Design", "Journalism & Mass Communication", "Information Technology", "Fashion Design", "Psychology", "Education", "Law"],
    tuitionMin: 10900,
    tuitionMax: 20200,
    hasDormitory: true,
    website: "https://amityuniversity.ae",
    founded: 2011,
    studentCount: 2500,
    internationalStudents: 2200,
    language: "English",
    description: "Первый частный университет в Дубае с WASC-аккредитацией. Часть индийской Amity Education Group. 125+ программ бакалавриата и магистратуры со стипендиями до 50%.",
    features: ["Первый вуз Дубая с WASC-аккредитацией", "CAA и KHDA аккредитация", "Стипендии до 50%", "125+ программ", "Forbes Top Education Provider"],
  },
]

async function main() {
  console.log('Seeding UAE universities...\n')

  for (const uni of uaeUniversities) {
    // Check if university already exists by name
    const existing = await prisma.internationalUniversity.findFirst({
      where: { name: uni.name },
    })

    if (existing) {
      // Update existing
      await prisma.internationalUniversity.update({
        where: { id: existing.id },
        data: uni,
      })
      console.log(`Updated: ${uni.name}`)
    } else {
      // Create new
      await prisma.internationalUniversity.create({
        data: uni,
      })
      console.log(`Created: ${uni.name}`)
    }
  }

  console.log(`\nDone! Processed ${uaeUniversities.length} UAE universities.`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
