import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const turkeyUniversities = [
  // === ОБНОВЛЕНИЕ СУЩЕСТВУЮЩИХ 5 ===
  {
    name: "Istanbul Technical University",
    country: "Турция",
    city: "Стамбул",
    worldRanking: "QS #298 (2026)",
    topMajors: ["Aerospace Engineering", "Architecture", "Computer Engineering", "Electrical & Electronics Engineering", "Civil Engineering", "Mechanical Engineering", "Naval Architecture", "Chemical Engineering"],
    allMajors: ["Aerospace Engineering", "Architecture", "Computer Engineering", "Electrical & Electronics Engineering", "Civil Engineering", "Mechanical Engineering", "Naval Architecture", "Chemical Engineering", "Industrial Engineering", "Geomatics Engineering", "Metallurgical & Materials Engineering", "Mathematics Engineering", "Physics Engineering", "Molecular Biology & Genetics", "Management Engineering", "Maritime Transportation"],
    tuitionMin: 600,
    tuitionMax: 6000,
    hasDormitory: true,
    website: "https://www.itu.edu.tr",
    founded: 1773,
    studentCount: 30000,
    internationalStudents: 5000,
    language: "Turkish/English",
    description: "Стамбульский технический университет — один из старейших технических вузов в мире (1773). Входит в топ-300 мирового рейтинга QS. Готовит ведущих инженеров и архитекторов Турции. 13 факультетов и 39 кафедр.",
    features: ["Старейший технический вуз Турции (1773)", "Топ-100 QS по инженерии", "Программы на английском языке", "Кампус в центре Стамбула (Maslak)", "ABET-аккредитация инженерных программ"],
  },
  {
    name: "Koç University",
    country: "Турция",
    city: "Стамбул",
    worldRanking: "QS #323 (2026)",
    topMajors: ["Business Administration", "Economics", "Computer Engineering", "Electrical & Electronics Engineering", "Industrial Engineering", "Medicine", "Law", "International Relations"],
    allMajors: ["Business Administration", "Economics", "Computer Engineering", "Electrical & Electronics Engineering", "Industrial Engineering", "Medicine", "Law", "International Relations", "Psychology", "Sociology", "Mathematics", "Physics", "Chemistry", "Molecular Biology & Genetics", "Mechanical Engineering", "Architecture", "Nursing"],
    tuitionMin: 18000,
    tuitionMax: 29000,
    hasDormitory: true,
    website: "https://www.ku.edu.tr",
    founded: 1993,
    studentCount: 7000,
    internationalStudents: 1400,
    language: "English",
    description: "Коч Университет — ведущий частный исследовательский вуз Турции. Полностью англоязычное обучение. Основан семьёй Коч — крупнейшим промышленным конгломератом Турции. Стипендии до 100% для лучших студентов.",
    features: ["100% англоязычное обучение", "Стипендии до 100%", "AACSB и EQUIS аккредитация бизнес-школы", "Современный кампус на берегу Босфора", "#1 частный вуз Турции по исследованиям"],
  },
  {
    name: "Bilkent University",
    country: "Турция",
    city: "Анкара",
    worldRanking: "QS #415 (2026)",
    topMajors: ["Computer Engineering", "Electrical & Electronics Engineering", "Industrial Engineering", "Business Administration", "Economics", "International Relations", "Architecture", "Music"],
    allMajors: ["Computer Engineering", "Electrical & Electronics Engineering", "Industrial Engineering", "Business Administration", "Economics", "International Relations", "Architecture", "Music", "Graphic Design", "Mathematics", "Physics", "Chemistry", "Molecular Biology & Genetics", "Law", "Tourism & Hotel Management"],
    tuitionMin: 16200,
    tuitionMax: 17000,
    hasDormitory: true,
    website: "https://www.bilkent.edu.tr",
    founded: 1984,
    studentCount: 13000,
    internationalStudents: 2000,
    language: "English",
    description: "Первый частный некоммерческий университет Турции. Полностью англоязычное обучение. Крупнейшая университетская библиотека в Турции. Кампус площадью 500 гектаров с развитой инфраструктурой.",
    features: ["Первый частный вуз Турции", "100% англоязычное обучение", "Крупнейшая университетская библиотека в стране", "500-гектарный кампус", "30% студентов на полных стипендиях"],
  },
  {
    name: "Hacettepe University",
    country: "Турция",
    city: "Анкара",
    worldRanking: "QS #511-520 (2026)",
    topMajors: ["Medicine", "Pharmacy", "Dentistry", "Engineering", "Health Sciences", "Education", "Fine Arts", "Economics"],
    allMajors: ["Medicine", "Pharmacy", "Dentistry", "Nursing", "Health Sciences", "Computer Engineering", "Electrical & Electronics Engineering", "Chemistry", "Biology", "Physics", "Economics", "Education", "Fine Arts", "Communication", "Law", "Social Work"],
    tuitionMin: 200,
    tuitionMax: 7000,
    hasDormitory: true,
    website: "https://www.hacettepe.edu.tr",
    founded: 1967,
    studentCount: 45000,
    internationalStudents: 5000,
    language: "Turkish/English",
    description: "Хаджеттепе — один из ведущих государственных университетов Турции, особенно известен своей медицинской школой. Располагает крупнейшей университетской клиникой страны. 16 факультетов.",
    features: ["Лучшая медицинская школа Турции", "Крупнейшая университетская клиника", "Государственный вуз — низкая стоимость", "16 факультетов", "Программы на английском языке"],
  },
  {
    name: "Istanbul University",
    country: "Турция",
    city: "Стамбул",
    worldRanking: "QS #801-850 (2026)",
    topMajors: ["Medicine", "Law", "Pharmacy", "Dentistry", "Economics", "Literature", "Engineering", "Political Science"],
    allMajors: ["Medicine", "Law", "Pharmacy", "Dentistry", "Economics", "Literature", "Engineering", "Political Science", "Theology", "Aquatic Sciences", "Forestry", "Communication", "Business Administration", "Health Sciences", "Transportation"],
    tuitionMin: 200,
    tuitionMax: 10800,
    hasDormitory: true,
    website: "https://www.istanbul.edu.tr",
    founded: 1453,
    studentCount: 60000,
    internationalStudents: 8000,
    language: "Turkish/English",
    description: "Старейший университет Турции, основанный в 1453 году. Крупнейший вуз страны с более чем 60 000 студентов. Расположен в историческом центре Стамбула. 17 факультетов.",
    features: ["Старейший университет Турции (1453)", "Крупнейший вуз страны", "Историческое расположение в центре Стамбула", "17 факультетов", "Государственный — доступная стоимость"],
  },

  // === НОВЫЕ 25 ВУЗОВ ===
  {
    name: "Middle East Technical University (METU)",
    country: "Турция",
    city: "Анкара",
    worldRanking: "QS #269 (2026)",
    topMajors: ["Computer Engineering", "Electrical & Electronics Engineering", "Mechanical Engineering", "Chemical Engineering", "Industrial Engineering", "Architecture", "Physics", "Mathematics"],
    allMajors: ["Computer Engineering", "Electrical & Electronics Engineering", "Mechanical Engineering", "Chemical Engineering", "Industrial Engineering", "Architecture", "Physics", "Mathematics", "Aerospace Engineering", "Civil Engineering", "Environmental Engineering", "Economics", "Business Administration", "International Relations", "Psychology", "Sociology", "Statistics", "Biology", "Chemistry", "Food Engineering"],
    tuitionMin: 600,
    tuitionMax: 6000,
    hasDormitory: true,
    website: "https://www.metu.edu.tr",
    founded: 1956,
    studentCount: 27000,
    internationalStudents: 5500,
    language: "English",
    description: "METU — ведущий государственный технический университет Турции, #1 в стране по инженерии и технологиям. Полностью англоязычное обучение. Самый зелёный кампус — 11 000 акров леса.",
    features: ["#1 инженерный вуз Турции", "100% англоязычное обучение", "Кампус 11 000 акров с озером и лесом", "ABET-аккредитация", "Более 100 стран среди студентов"],
  },
  {
    name: "Boğaziçi University",
    country: "Турция",
    city: "Стамбул",
    worldRanking: "QS #371 (2026)",
    topMajors: ["Computer Engineering", "Electrical & Electronics Engineering", "Industrial Engineering", "Management", "Economics", "Physics", "Mathematics", "Chemistry"],
    allMajors: ["Computer Engineering", "Electrical & Electronics Engineering", "Industrial Engineering", "Management", "Economics", "Physics", "Mathematics", "Chemistry", "Mechanical Engineering", "Chemical Engineering", "Civil Engineering", "Translation & Interpreting", "Psychology", "Political Science", "History", "Philosophy", "Linguistics", "Molecular Biology & Genetics"],
    tuitionMin: 200,
    tuitionMax: 5000,
    hasDormitory: true,
    website: "https://www.bogazici.edu.tr",
    founded: 1863,
    studentCount: 17000,
    internationalStudents: 2500,
    language: "English",
    description: "Богазичи — самый престижный государственный вуз Турции, основанный как Robert College в 1863 году. 100% англоязычное обучение. Кампус на берегу Босфора — один из красивейших в мире.",
    features: ["Самый селективный вуз Турции", "100% англоязычное обучение", "Кампус с видом на Босфор", "Основан как Robert College (1863)", "Государственный — низкая стоимость"],
  },
  {
    name: "Sabancı University",
    country: "Турция",
    city: "Стамбул",
    worldRanking: "QS #404 (2026)",
    topMajors: ["Computer Science & Engineering", "Electronics Engineering", "Mechatronics", "Industrial Engineering", "Management", "Economics", "Political Science", "Visual Arts & Visual Communication Design"],
    allMajors: ["Computer Science & Engineering", "Electronics Engineering", "Mechatronics Engineering", "Industrial Engineering", "Manufacturing Systems Engineering", "Management", "Economics", "Political Science", "Visual Arts & Visual Communication Design", "Cultural Studies", "Mathematics", "Molecular Biology & Genetics", "Materials Science"],
    tuitionMin: 20000,
    tuitionMax: 24000,
    hasDormitory: true,
    website: "https://www.sabanciuniv.edu",
    founded: 1994,
    studentCount: 5000,
    internationalStudents: 1000,
    language: "English",
    description: "Сабанджи — частный исследовательский университет, один из самых инновационных вузов Турции. Уникальная междисциплинарная учебная модель. Стипендии до 100%.",
    features: ["100% англоязычное обучение", "Междисциплинарная модель обучения", "Стипендии до 100%", "Современный кампус в Tuzla", "Сильные связи с индустрией Sabancı Group"],
  },
  {
    name: "Ankara University",
    country: "Турция",
    city: "Анкара",
    worldRanking: "QS #591-600 (2026)",
    topMajors: ["Medicine", "Law", "Political Science", "Agriculture", "Veterinary Medicine", "Pharmacy", "Dentistry", "Science"],
    allMajors: ["Medicine", "Law", "Political Science", "Agriculture", "Veterinary Medicine", "Pharmacy", "Dentistry", "Science", "Engineering", "Communication", "Theology", "Language & History-Geography", "Education", "Health Sciences", "Fine Arts"],
    tuitionMin: 200,
    tuitionMax: 6000,
    hasDormitory: true,
    website: "https://www.ankara.edu.tr",
    founded: 1946,
    studentCount: 65000,
    internationalStudents: 7000,
    language: "Turkish/English",
    description: "Анкарский университет — первый вуз Турецкой Республики, основанный в 1946 году. 20 факультетов. Сильные программы в медицине, праве и сельском хозяйстве.",
    features: ["Первый университет Турецкой Республики", "20 факультетов", "Крупнейший вуз Анкары", "Государственный — доступная стоимость", "Исторический кампус в центре города"],
  },
  {
    name: "Yıldız Technical University",
    country: "Турция",
    city: "Стамбул",
    worldRanking: "QS #551-560 (2026)",
    topMajors: ["Computer Engineering", "Electrical Engineering", "Mechanical Engineering", "Civil Engineering", "Chemical Engineering", "Architecture", "Industrial Engineering", "Mathematics"],
    allMajors: ["Computer Engineering", "Electrical Engineering", "Mechanical Engineering", "Civil Engineering", "Chemical Engineering", "Architecture", "Industrial Engineering", "Mathematics", "Physics", "Environmental Engineering", "Metallurgical Engineering", "Naval Architecture", "Bioengineering", "Art & Design"],
    tuitionMin: 200,
    tuitionMax: 4000,
    hasDormitory: true,
    website: "https://www.yildiz.edu.tr",
    founded: 1911,
    studentCount: 25000,
    internationalStudents: 3000,
    language: "Turkish/English",
    description: "Йылдыз — второй по старшинству технический университет Стамбула. 11 факультетов с акцентом на инженерию и технологии. Два кампуса: исторический Бешикташ и современный Давутпаша.",
    features: ["Второй старейший технический вуз Стамбула", "Исторический кампус в Бешикташ", "Сильные инженерные программы", "Государственный — низкая стоимость", "Удобное расположение в центре Стамбула"],
  },
  {
    name: "Marmara University",
    country: "Турция",
    city: "Стамбул",
    worldRanking: "QS #651-700 (2026)",
    topMajors: ["Medicine", "Dentistry", "Pharmacy", "Engineering", "Law", "Business Administration", "Economics", "Communication"],
    allMajors: ["Medicine", "Dentistry", "Pharmacy", "Engineering", "Law", "Business Administration", "Economics", "Communication", "Education", "Theology", "Fine Arts", "Health Sciences", "Technology", "Architecture", "Political Science"],
    tuitionMin: 200,
    tuitionMax: 5000,
    hasDormitory: true,
    website: "https://www.marmara.edu.tr",
    founded: 1883,
    studentCount: 60000,
    internationalStudents: 5000,
    language: "Turkish/English/Arabic",
    description: "Мармара — один из крупнейших государственных вузов Турции с программами на 4 языках: турецком, английском, арабском и немецком. 16 факультетов в 7 кампусах.",
    features: ["Обучение на 4 языках", "16 факультетов", "7 кампусов по Стамбулу", "Один из крупнейших вузов Турции", "Государственный — доступная стоимость"],
  },
  {
    name: "Galatasaray University",
    country: "Турция",
    city: "Стамбул",
    worldRanking: "QS #801-850 (2026)",
    topMajors: ["Law", "Economics", "International Relations", "Management", "Computer Engineering", "Industrial Engineering", "Communication", "Philosophy"],
    allMajors: ["Law", "Economics", "International Relations", "Management", "Computer Engineering", "Industrial Engineering", "Communication", "Philosophy", "Sociology", "Political Science", "Mathematics"],
    tuitionMin: 200,
    tuitionMax: 3000,
    hasDormitory: false,
    website: "https://www.gsu.edu.tr",
    founded: 1992,
    studentCount: 3500,
    internationalStudents: 400,
    language: "French/Turkish",
    description: "Галатасарай — уникальный турецко-французский государственный вуз с обучением на французском языке. Основан на базе исторического лицея Галатасарай (1481). Селективный приём.",
    features: ["Обучение на французском языке", "Турецко-французский вуз", "Историческая традиция лицея Галатасарай", "Кампус в Ортакёй с видом на Босфор", "Государственный — низкая стоимость"],
  },
  {
    name: "Ege University",
    country: "Турция",
    city: "Измир",
    worldRanking: "QS #651-700 (2026)",
    topMajors: ["Medicine", "Pharmacy", "Engineering", "Agriculture", "Science", "Dentistry", "Nursing", "Economics"],
    allMajors: ["Medicine", "Pharmacy", "Engineering", "Agriculture", "Science", "Dentistry", "Nursing", "Economics", "Communication", "Education", "Fisheries", "Literature", "Health Sciences", "Computer Science"],
    tuitionMin: 200,
    tuitionMax: 6000,
    hasDormitory: true,
    website: "https://www.ege.edu.tr",
    founded: 1955,
    studentCount: 50000,
    internationalStudents: 4000,
    language: "Turkish/English",
    description: "Эгейский университет — крупнейший вуз Измира и один из ведущих государственных университетов Турции. Особенно силён в медицине, фармации и сельском хозяйстве. 17 факультетов.",
    features: ["Крупнейший вуз Измира", "17 факультетов", "Сильные медицинские программы", "Кампус площадью 3 500 гектаров", "Государственный — доступная стоимость"],
  },
  {
    name: "Dokuz Eylül University",
    country: "Турция",
    city: "Измир",
    worldRanking: "QS #801-850 (2026)",
    topMajors: ["Medicine", "Engineering", "Business Administration", "Maritime", "Fine Arts", "Architecture", "Law", "Economics"],
    allMajors: ["Medicine", "Engineering", "Business Administration", "Maritime", "Fine Arts", "Architecture", "Law", "Economics", "Education", "Nursing", "Science", "Literature", "Theology", "Tourism", "Fisheries"],
    tuitionMin: 200,
    tuitionMax: 5000,
    hasDormitory: true,
    website: "https://www.deu.edu.tr",
    founded: 1982,
    studentCount: 45000,
    internationalStudents: 3000,
    language: "Turkish/English",
    description: "Докуз Эйлюль — один из ведущих государственных вузов Измира. Известен сильными программами в морском деле, медицине и искусстве. 17 факультетов.",
    features: ["Ведущая морская программа Турции", "17 факультетов", "Несколько кампусов в Измире", "Государственный — доступная стоимость", "Сильные программы искусства и дизайна"],
  },
  {
    name: "Gazi University",
    country: "Турция",
    city: "Анкара",
    worldRanking: "QS #601-650 (2026)",
    topMajors: ["Medicine", "Dentistry", "Pharmacy", "Engineering", "Education", "Architecture", "Health Sciences", "Technology"],
    allMajors: ["Medicine", "Dentistry", "Pharmacy", "Engineering", "Education", "Architecture", "Health Sciences", "Technology", "Economics & Administrative Sciences", "Communication", "Law", "Fine Arts", "Sports Science", "Tourism"],
    tuitionMin: 200,
    tuitionMax: 5000,
    hasDormitory: true,
    website: "https://gazi.edu.tr",
    founded: 1926,
    studentCount: 50000,
    internationalStudents: 5000,
    language: "Turkish/English",
    description: "Гази — один из старейших и крупнейших государственных вузов Турции. Основан Ататюрком в 1926 году. Особенно известен программами в медицине и образовании.",
    features: ["Основан Ататюрком (1926)", "Один из крупнейших вузов Турции", "Сильная медицинская школа", "Государственный — доступная стоимость", "Богатая история и традиции"],
  },
  {
    name: "Izmir Institute of Technology (IZTECH)",
    country: "Турция",
    city: "Измир",
    worldRanking: "QS #801-850 (2026)",
    topMajors: ["Computer Engineering", "Molecular Biology & Genetics", "Chemical Engineering", "Architecture", "Physics", "Mathematics", "Environmental Engineering", "Electronics Engineering"],
    allMajors: ["Computer Engineering", "Molecular Biology & Genetics", "Chemical Engineering", "Architecture", "Physics", "Mathematics", "Environmental Engineering", "Electronics Engineering", "Mechanical Engineering", "Civil Engineering", "Food Engineering", "Materials Science", "Chemistry", "City & Regional Planning"],
    tuitionMin: 200,
    tuitionMax: 4000,
    hasDormitory: true,
    website: "https://www.iyte.edu.tr",
    founded: 1992,
    studentCount: 5000,
    internationalStudents: 600,
    language: "English",
    description: "IZTECH — единственный государственный технический вуз Измира. 100% англоязычное обучение. Небольшой, но исследовательски ориентированный вуз. Кампус площадью 3 500 гектаров в Урле.",
    features: ["100% англоязычное обучение", "Государственный технический вуз", "Исследовательская ориентация", "Кампус 3 500 га в Урле", "Небольшие группы — персонализированное обучение"],
  },
  {
    name: "Gebze Technical University",
    country: "Турция",
    city: "Коджаэли",
    worldRanking: "QS #801-1000 (2026)",
    topMajors: ["Computer Engineering", "Electronics Engineering", "Materials Science", "Chemistry", "Physics", "Mathematics", "Molecular Biology", "Environmental Engineering"],
    allMajors: ["Computer Engineering", "Electronics Engineering", "Materials Science & Engineering", "Chemistry", "Physics", "Mathematics", "Molecular Biology & Genetics", "Environmental Engineering", "Energy Systems Engineering", "Architecture", "Business Administration"],
    tuitionMin: 200,
    tuitionMax: 3000,
    hasDormitory: true,
    website: "https://www.gtu.edu.tr",
    founded: 1992,
    studentCount: 5500,
    internationalStudents: 700,
    language: "English",
    description: "Гебзе — государственный технический вуз близ Стамбула, ориентированный на исследования в науке и технологиях. 100% англоязычное обучение. Сильные связи с промышленной зоной Гебзе.",
    features: ["100% англоязычное обучение", "Исследовательский фокус", "Близость к промышленной зоне Гебзе", "Государственный — низкая стоимость", "40 минут от Стамбула"],
  },
  {
    name: "TED University",
    country: "Турция",
    city: "Анкара",
    worldRanking: "QS #801-1000 (2026)",
    topMajors: ["Computer Engineering", "Electrical & Electronics Engineering", "Architecture", "Economics", "Psychology", "Business Administration", "Industrial Design", "Interior Architecture"],
    allMajors: ["Computer Engineering", "Electrical & Electronics Engineering", "Architecture", "Economics", "Psychology", "Business Administration", "Industrial Design", "Interior Architecture", "Mathematics", "Education", "English Language & Literature", "Political Science"],
    tuitionMin: 12000,
    tuitionMax: 16000,
    hasDormitory: true,
    website: "https://www.tedu.edu.tr",
    founded: 2009,
    studentCount: 4000,
    internationalStudents: 500,
    language: "English",
    description: "TED Университет — молодой частный вуз, основанный Турецким образовательным обществом (TED). 100% англоязычное обучение. Индивидуальный подход благодаря малым группам.",
    features: ["100% англоязычное обучение", "Основан Турецким образовательным обществом", "Малые группы — индивидуальный подход", "Стипендии до 100%", "Современный кампус в Анкаре"],
  },
  {
    name: "Özyeğin University",
    country: "Турция",
    city: "Стамбул",
    worldRanking: "QS #571-580 (2026)",
    topMajors: ["Computer Science", "Electrical & Electronics Engineering", "Industrial Engineering", "Business Administration", "Architecture", "Law", "Aviation Management", "Gastronomy"],
    allMajors: ["Computer Science", "Electrical & Electronics Engineering", "Industrial Engineering", "Business Administration", "Architecture", "Law", "Aviation Management", "Gastronomy & Culinary Arts", "International Finance", "Psychology", "Entrepreneurship", "Mechanical Engineering", "Civil Engineering", "Interior Architecture"],
    tuitionMin: 14000,
    tuitionMax: 19000,
    hasDormitory: true,
    website: "https://www.ozyegin.edu.tr",
    founded: 2007,
    studentCount: 7000,
    internationalStudents: 800,
    language: "English",
    description: "Озйегин — инновационный частный университет Стамбула. Одна из лучших бизнес-школ Турции с тройной аккредитацией. Уникальные программы в гастрономии и авиации.",
    features: ["AACSB, AMBA и EQUIS тройная аккредитация бизнес-школы", "100% англоязычное обучение", "Уникальные программы: гастрономия, авиация", "Стипендии до 100%", "Современный кампус в Чекмекёй"],
  },
  {
    name: "Bahçeşehir University (BAU)",
    country: "Турция",
    city: "Стамбул",
    worldRanking: "QS #601-650 (2026)",
    topMajors: ["Computer Engineering", "Software Engineering", "Architecture", "Digital Game Design", "Film & Television", "Medicine", "Dentistry", "International Relations"],
    allMajors: ["Computer Engineering", "Software Engineering", "Architecture", "Digital Game Design", "Film & Television", "Medicine", "Dentistry", "International Relations", "Law", "Communication", "Business Administration", "Psychology", "Industrial Engineering", "Interior Architecture", "Graphic Design", "Economics"],
    tuitionMin: 8500,
    tuitionMax: 25000,
    hasDormitory: true,
    website: "https://bau.edu.tr",
    founded: 1998,
    studentCount: 25000,
    internationalStudents: 5000,
    language: "Turkish/English",
    description: "BAU — крупный частный вуз с кампусом в центре Стамбула (Бешикташ). Часть BAU Global — образовательной сети с кампусами в Берлине, Вашингтоне, Торонто. Программы обмена в 40+ странах.",
    features: ["Кампус в центре Стамбула (Бешикташ)", "Глобальная сеть BAU Global", "Кампусы в Берлине, Вашингтоне, Торонто", "Программы обмена в 40+ странах", "Сильные программы в медиа и дизайне"],
  },
  {
    name: "Istanbul Bilgi University",
    country: "Турция",
    city: "Стамбул",
    worldRanking: "QS #801-1000 (2026)",
    topMajors: ["Computer Engineering", "Law", "Business Administration", "Communication", "Film & Television", "Architecture", "International Relations", "Psychology"],
    allMajors: ["Computer Engineering", "Law", "Business Administration", "Communication", "Film & Television", "Architecture", "International Relations", "Psychology", "Music", "Performing Arts", "Energy Systems Engineering", "Genetics & Bioengineering", "Marketing", "Economics", "Sociology"],
    tuitionMin: 7500,
    tuitionMax: 16000,
    hasDormitory: true,
    website: "https://www.bilgi.edu.tr",
    founded: 1996,
    studentCount: 15000,
    internationalStudents: 2000,
    language: "Turkish/English",
    description: "Bilgi — частный вуз с 3 кампусами в Стамбуле, часть Laureate International Universities. Известен сильными программами в медиа, искусстве и юриспруденции.",
    features: ["3 кампуса в Стамбуле", "Часть Laureate International Universities", "Сильные программы в медиа и искусстве", "Стипендии до 100%", "Разнообразная студенческая жизнь"],
  },
  {
    name: "Kadir Has University",
    country: "Турция",
    city: "Стамбул",
    worldRanking: "QS #801-1000 (2026)",
    topMajors: ["Computer Engineering", "Management Information Systems", "Architecture", "Interior Architecture", "Film & Drama", "International Relations", "Law", "Economics"],
    allMajors: ["Computer Engineering", "Management Information Systems", "Architecture", "Interior Architecture", "Film & Drama", "International Relations", "Law", "Economics", "Industrial Design", "Graphic Design", "Communication", "New Media", "Business Administration", "Psychology", "Trading & Logistics"],
    tuitionMin: 9000,
    tuitionMax: 15000,
    hasDormitory: true,
    website: "https://www.khas.edu.tr",
    founded: 1997,
    studentCount: 7000,
    internationalStudents: 800,
    language: "English",
    description: "Кадир Хас — частный вуз с историческим кампусом в Джибали (Золотой Рог). Восстановленная табачная фабрика XIX века. 100% англоязычное обучение.",
    features: ["100% англоязычное обучение", "Исторический кампус — бывшая табачная фабрика", "Расположение на Золотом Роге", "Стипендии до 100%", "Небольшие группы — индивидуальный подход"],
  },
  {
    name: "Atılım University",
    country: "Турция",
    city: "Анкара",
    worldRanking: "QS #801-1000 (2026)",
    topMajors: ["Computer Engineering", "Software Engineering", "Electrical & Electronics Engineering", "Mechatronics Engineering", "Industrial Engineering", "Law", "Business Administration", "Aviation Management"],
    allMajors: ["Computer Engineering", "Software Engineering", "Electrical & Electronics Engineering", "Mechatronics Engineering", "Industrial Engineering", "Law", "Business Administration", "Aviation Management", "Metallurgical Engineering", "Automotive Engineering", "Civil Engineering", "Architecture", "Interior Architecture", "Nursing", "Political Science"],
    tuitionMin: 10000,
    tuitionMax: 14000,
    hasDormitory: true,
    website: "https://www.atilim.edu.tr",
    founded: 1996,
    studentCount: 9000,
    internationalStudents: 1500,
    language: "English",
    description: "Атылым — частный вуз при Фонде Атылым в Анкаре. 100% англоязычное обучение. Сильные инженерные программы и связи с промышленной зоной Анкары.",
    features: ["100% англоязычное обучение", "ABET-аккредитация инженерных программ", "Кампус с развитой инфраструктурой", "Стипендии до 100%", "Связи с оборонной промышленностью Анкары"],
  },
  {
    name: "TOBB University of Economics and Technology",
    country: "Турция",
    city: "Анкара",
    worldRanking: "QS #801-1000 (2026)",
    topMajors: ["Computer Engineering", "Electrical & Electronics Engineering", "Industrial Engineering", "Business Administration", "Economics", "Law", "International Relations", "Biomedical Engineering"],
    allMajors: ["Computer Engineering", "Electrical & Electronics Engineering", "Industrial Engineering", "Business Administration", "Economics", "Law", "International Relations", "Biomedical Engineering", "Mechanical Engineering", "Architecture", "Mathematics", "History", "English Language & Literature", "Political Science"],
    tuitionMin: 11000,
    tuitionMax: 15000,
    hasDormitory: true,
    website: "https://www.etu.edu.tr",
    founded: 2003,
    studentCount: 5500,
    internationalStudents: 600,
    language: "English",
    description: "TOBB ETU — частный вуз, основанный Союзом торговых палат Турции. 100% англоязычное обучение. Тесные связи с бизнес-сообществом Турции.",
    features: ["100% англоязычное обучение", "Основан Союзом торговых палат Турции", "Тесные связи с бизнесом", "ABET-аккредитация", "Стипендии до 100%"],
  },
  {
    name: "Başkent University",
    country: "Турция",
    city: "Анкара",
    worldRanking: "QS #1001-1200 (2026)",
    topMajors: ["Medicine", "Dentistry", "Law", "Engineering", "Health Sciences", "Communication", "Education", "Fine Arts"],
    allMajors: ["Medicine", "Dentistry", "Law", "Computer Engineering", "Electrical & Electronics Engineering", "Industrial Engineering", "Biomedical Engineering", "Health Sciences", "Communication", "Education", "Fine Arts", "Economics", "Business Administration", "Nursing"],
    tuitionMin: 8000,
    tuitionMax: 22000,
    hasDormitory: true,
    website: "https://www.baskent.edu.tr",
    founded: 1994,
    studentCount: 10000,
    internationalStudents: 800,
    language: "Turkish/English",
    description: "Башкент — частный вуз, основанный профессором медицины. Сильнейшие медицинские программы и собственные университетские клиники. 11 факультетов.",
    features: ["Сильные медицинские программы", "Собственные университетские клиники", "11 факультетов", "Кампус в Баглыджа", "Стипендии до 50%"],
  },
  {
    name: "Istanbul Medipol University",
    country: "Турция",
    city: "Стамбул",
    worldRanking: "QS #801-1000 (2026)",
    topMajors: ["Medicine", "Dentistry", "Pharmacy", "Health Sciences", "Engineering", "Law", "Business Administration", "Communication"],
    allMajors: ["Medicine", "Dentistry", "Pharmacy", "Health Sciences", "Computer Engineering", "Electrical & Electronics Engineering", "Industrial Engineering", "Law", "Business Administration", "Communication", "Psychology", "Architecture", "Economics", "International Relations", "Biomedical Engineering"],
    tuitionMin: 6000,
    tuitionMax: 25000,
    hasDormitory: true,
    website: "https://www.medipol.edu.tr",
    founded: 2009,
    studentCount: 30000,
    internationalStudents: 5000,
    language: "Turkish/English",
    description: "Медиполь — крупный частный вуз с сильным фокусом на медицине и здравоохранении. Собственные университетские больницы — крупнейший частный госпитальный комплекс Турции.",
    features: ["Крупнейший частный госпитальный комплекс Турции", "12 факультетов", "Сильные медицинские программы", "Современная инфраструктура", "Стипендии до 75%"],
  },
  {
    name: "Altınbaş University",
    country: "Турция",
    city: "Стамбул",
    worldRanking: "QS #801-1000 (2026)",
    topMajors: ["Medicine", "Dentistry", "Pharmacy", "Engineering", "Architecture", "Law", "Business Administration", "Psychology"],
    allMajors: ["Medicine", "Dentistry", "Pharmacy", "Computer Engineering", "Software Engineering", "Electrical & Electronics Engineering", "Architecture", "Law", "Business Administration", "Psychology", "Economics", "Interior Architecture", "Graphic Design", "Nursing"],
    tuitionMin: 4500,
    tuitionMax: 22000,
    hasDormitory: true,
    website: "https://www.altinbas.edu.tr",
    founded: 2008,
    studentCount: 12000,
    internationalStudents: 3000,
    language: "Turkish/English",
    description: "Алтынбаш — частный вуз в Стамбуле, ранее известный как Istanbul Kemerburgaz University. Доступная стоимость обучения с сильными программами в медицине и инженерии.",
    features: ["Доступная стоимость обучения", "Кампус в Махмутбей (Стамбул)", "Сильные медицинские программы", "Стипендии до 100%", "Программы обмена с 200+ вузами"],
  },
  {
    name: "Beykent University",
    country: "Турция",
    city: "Стамбул",
    worldRanking: "QS #1001-1200 (2026)",
    topMajors: ["Architecture", "Interior Architecture", "Computer Engineering", "Industrial Design", "Business Administration", "Gastronomy", "Film & Television", "Communication"],
    allMajors: ["Architecture", "Interior Architecture", "Computer Engineering", "Industrial Design", "Business Administration", "Gastronomy & Culinary Arts", "Film & Television", "Communication", "Law", "Electrical & Electronics Engineering", "Software Engineering", "Psychology", "Economics", "Graphic Design", "Music"],
    tuitionMin: 4000,
    tuitionMax: 12000,
    hasDormitory: true,
    website: "https://www.beykent.edu.tr",
    founded: 1997,
    studentCount: 18000,
    internationalStudents: 3000,
    language: "Turkish/English",
    description: "Бейкент — доступный частный вуз с 3 кампусами в Стамбуле. Сильные программы в архитектуре, дизайне и гастрономии. Одна из самых низких цен среди частных вузов.",
    features: ["Одна из самых доступных цен среди частных вузов", "3 кампуса в Стамбуле", "Сильные программы дизайна и архитектуры", "Стипендии до 100%", "Программы на турецком и английском"],
  },
  {
    name: "Yeditepe University",
    country: "Турция",
    city: "Стамбул",
    worldRanking: "QS #801-1000 (2026)",
    topMajors: ["Medicine", "Dentistry", "Pharmacy", "Engineering", "Law", "Architecture", "Fine Arts", "Business Administration"],
    allMajors: ["Medicine", "Dentistry", "Pharmacy", "Computer Engineering", "Electrical & Electronics Engineering", "Food Engineering", "Genetics & Bioengineering", "Law", "Architecture", "Fine Arts", "Business Administration", "Communication", "Economics", "Education", "Health Sciences"],
    tuitionMin: 7000,
    tuitionMax: 23000,
    hasDormitory: true,
    website: "https://www.yeditepe.edu.tr",
    founded: 1996,
    studentCount: 20000,
    internationalStudents: 3000,
    language: "Turkish/English",
    description: "Йедитепе — частный вуз с крупным кампусом на азиатской стороне Стамбула. 13 факультетов. Собственная университетская больница и стоматологическая клиника.",
    features: ["13 факультетов", "Собственная больница и стоматологическая клиника", "Кампус 222 гектара в Ataşehir", "200+ программ обмена", "Стипендии до 100%"],
  },
  {
    name: "Antalya Bilim University",
    country: "Турция",
    city: "Анталья",
    worldRanking: "QS #1201+ (2026)",
    topMajors: ["Aviation Management", "Tourism & Hotel Management", "Gastronomy", "Computer Engineering", "Industrial Engineering", "Business Administration", "International Relations", "Architecture"],
    allMajors: ["Aviation Management", "Tourism & Hotel Management", "Gastronomy & Culinary Arts", "Computer Engineering", "Industrial Engineering", "Business Administration", "International Relations", "Architecture", "Interior Architecture", "Civil Engineering", "Electrical & Electronics Engineering", "Law", "Psychology", "Nursing"],
    tuitionMin: 5000,
    tuitionMax: 10000,
    hasDormitory: true,
    website: "https://www.antalya.edu.tr",
    founded: 2012,
    studentCount: 4000,
    internationalStudents: 800,
    language: "Turkish/English",
    description: "Антальа Билим — молодой частный вуз на средиземноморском побережье Турции. Уникальные программы в авиации и туризме. Расположен на берегу моря.",
    features: ["Кампус на берегу Средиземного моря", "Уникальные программы авиации и туризма", "Доступная стоимость обучения", "Стипендии до 100%", "Международная студенческая среда"],
  },
]

async function main() {
  console.log('Seeding Turkish universities...\n')

  for (const uni of turkeyUniversities) {
    // Check if university already exists by name
    const existing = await prisma.internationalUniversity.findFirst({
      where: { name: uni.name },
    })

    if (existing) {
      // Update existing
      await prisma.internationalUniversity.update({
        where: { id: existing.id },
        data: uni,
      })
      console.log(`Updated: ${uni.name}`)
    } else {
      // Create new
      await prisma.internationalUniversity.create({
        data: uni,
      })
      console.log(`Created: ${uni.name}`)
    }
  }

  console.log(`\nDone! Processed ${turkeyUniversities.length} Turkish universities.`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
